
package com.skywell.banking.api.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.skywell.banking.api.ws.product.BankDepositListRp;
import com.skywell.banking.api.ws.product.OperRp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DepositWebService", targetNamespace = "http://cb.ukrpay.net/common/ws")
@XmlSeeAlso({
        com.skywell.banking.api.ws.ObjectFactory.class,
        com.skywell.banking.api.ws.product.ObjectFactory.class,
        com.skywell.banking.api.ws.user.ObjectFactory.class
})
public interface DepositWebService {


    /**
     * 
     * @param reqBase
     * @return
     *     returns net.ukrpay.cb.common.ws.product.BankDepositListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/product")
    @RequestWrapper(localName = "getBankDepositListAllowOpen", targetNamespace = "http://cb.ukrpay.net/common/ws/product", className = "com.skywell.banking.api.ws.product.GetBankDepositListAllowOpen")
    @ResponseWrapper(localName = "getBankDepositListAllowOpenResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/product", className = "com.skywell.banking.api.ws.product.GetBankDepositListAllowOpenResponse")
    public BankDepositListRp getBankDepositListAllowOpen(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/product")
        ReqBase reqBase);

    /**
     * 
     * @param bankProductId
     * @param operAmount
     * @param bankDepositPeriodId
     * @param clientProductId
     * @param operCurrencyId
     * @param reqBase
     * @return
     *     returns com.skywell.banking.api.ws.product.OperRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/product")
    @RequestWrapper(localName = "createBankDepositOpen", targetNamespace = "http://cb.ukrpay.net/common/ws/product", className = "com.skywell.banking.api.ws.product.CreateBankDepositOpen")
    @ResponseWrapper(localName = "createBankDepositOpenResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/product", className = "com.skywell.banking.api.ws.product.CreateBankDepositOpenResponse")
    public OperRp createBankDepositOpen(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/product")
        ReqBase reqBase,
        @WebParam(name = "bankProductId", targetNamespace = "http://cb.ukrpay.net/common/ws/product")
        int bankProductId,
        @WebParam(name = "bankDepositPeriodId", targetNamespace = "http://cb.ukrpay.net/common/ws/product")
        int bankDepositPeriodId,
        @WebParam(name = "operAmount", targetNamespace = "http://cb.ukrpay.net/common/ws/product")
        long operAmount,
        @WebParam(name = "operCurrencyId", targetNamespace = "http://cb.ukrpay.net/common/ws/product")
        int operCurrencyId,
        @WebParam(name = "clientProductId", targetNamespace = "http://cb.ukrpay.net/common/ws/product")
        long clientProductId);

}
