
package com.skywell.banking.api.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DepositWebService", targetNamespace = "http://cb.ukrpay.net/common/ws", wsdlLocation = "http://10.1.15.19:7001/backend/common/depositapi/?wsdl")
public class DepositWebService_Service extends Service {

    private final static URL DEPOSITWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEPOSITWEBSERVICE_EXCEPTION;
    private final static QName DEPOSITWEBSERVICE_QNAME = new QName("http://cb.ukrpay.net/common/ws",
            "DepositWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.15.19:7001/backend/common/depositapi/?wsdl");
        } catch (MalformedURLException e1) {
            e1.printStackTrace();
        }
        DEPOSITWEBSERVICE_WSDL_LOCATION = url;
        DEPOSITWEBSERVICE_EXCEPTION = e;
    }

    public DepositWebService_Service() {
        super(__getWsdlLocation(), DEPOSITWEBSERVICE_QNAME);
    }

    public DepositWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPOSITWEBSERVICE_QNAME, features);
    }

    public DepositWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, DEPOSITWEBSERVICE_QNAME);
    }

    public DepositWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPOSITWEBSERVICE_QNAME, features);
    }

    public DepositWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepositWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns DepositWebService
     */
    @WebEndpoint(name = "DepositWebServiceSOAPHttpPort")
    public DepositWebService getDepositWebServiceSOAPHttpPort() {
        return super.getPort(new QName("http://cb.ukrpay.net/common/ws", "DepositWebServiceSOAPHttpPort"),
                DepositWebService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns DepositWebService
     */
    @WebEndpoint(name = "DepositWebServiceSOAPHttpPort")
    public DepositWebService getDepositWebServiceSOAPHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cb.ukrpay.net/common/ws", "DepositWebServiceSOAPHttpPort"),
                DepositWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPOSITWEBSERVICE_EXCEPTION != null) {
            throw DEPOSITWEBSERVICE_EXCEPTION;
        }
        return DEPOSITWEBSERVICE_WSDL_LOCATION;
    }

}
