
package com.skywell.banking.api.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductWebService", targetNamespace = "http://cb.ukrpay.net/common/ws", wsdlLocation = "http://10.1.15.19:7001/backend/common/productapi/?wsdl")
public class ProductWebService_Service extends Service {

    private final static URL PRODUCTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTWEBSERVICE_EXCEPTION;
    private final static QName PRODUCTWEBSERVICE_QNAME = new QName("http://cb.ukrpay.net/common/ws",
            "ProductWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.15.19:7001/backend/common/productapi/?wsdl");
        } catch (MalformedURLException e1) {
            e1.printStackTrace();
        }
        PRODUCTWEBSERVICE_WSDL_LOCATION = url;
        PRODUCTWEBSERVICE_EXCEPTION = e;
    }

    public ProductWebService_Service() {
        super(__getWsdlLocation(), PRODUCTWEBSERVICE_QNAME);
    }

    public ProductWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTWEBSERVICE_QNAME, features);
    }

    public ProductWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTWEBSERVICE_QNAME);
    }

    public ProductWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTWEBSERVICE_QNAME, features);
    }

    public ProductWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns ProductWebService
     */
    @WebEndpoint(name = "ProductWebServiceSOAPHttpPort")
    public ProductWebService getProductWebServiceSOAPHttpPort() {
        return super.getPort(new QName("http://cb.ukrpay.net/common/ws", "ProductWebServiceSOAPHttpPort"),
                ProductWebService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns ProductWebService
     */
    @WebEndpoint(name = "ProductWebServiceSOAPHttpPort")
    public ProductWebService getProductWebServiceSOAPHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cb.ukrpay.net/common/ws", "ProductWebServiceSOAPHttpPort"),
                ProductWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTWEBSERVICE_EXCEPTION != null) {
            throw PRODUCTWEBSERVICE_EXCEPTION;
        }
        return PRODUCTWEBSERVICE_WSDL_LOCATION;
    }

}
