
package com.skywell.banking.api.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.skywell.banking.api.ws.serv.AttrValue;
import com.skywell.banking.api.ws.serv.CategoryListRp;
import com.skywell.banking.api.ws.serv.ServInfoRp;
import com.skywell.banking.api.ws.serv.ServOperRp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServWebService", targetNamespace = "http://cb.ukrpay.net/common/ws")
@XmlSeeAlso({
        com.skywell.banking.api.ws.ObjectFactory.class,
        com.skywell.banking.api.ws.serv.ObjectFactory.class
})
public interface ServWebService {


    /**
     * 
     * @param reqBase
     * @param parentId
     * @return
     *     returns com.skywell.banking.api.ws.serv.CategoryListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
    @RequestWrapper(localName = "getCategoryList", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "com.skywell.banking.api.ws.serv.GetCategoryList")
    @ResponseWrapper(localName = "getCategoryListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "com.skywell.banking.api.ws.serv.GetCategoryListResponse")
    public CategoryListRp getCategoryList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        ReqBase reqBase,
        @WebParam(name = "parentId", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        int parentId);

    /**
     * 
     * @param reqBase
     * @param categoryId
     * @return
     *     returns com.skywell.banking.api.ws.serv.ServListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
    @RequestWrapper(localName = "getServList", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "com.skywell.banking.api.ws.serv.GetServList")
    @ResponseWrapper(localName = "getServListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "com.skywell.banking.api.ws.serv.GetServListResponse")
    public CategoryListRp getServList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        ReqBase reqBase,
        @WebParam(name = "categoryId", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        int categoryId);

    /**
     * 
     * @param servId
     * @param reqBase
     * @return
     *     returns com.skywell.banking.api.ws.serv.ServInfoRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
    @RequestWrapper(localName = "getServInfo", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "com.skywell.banking.api.ws.serv.GetServInfo")
    @ResponseWrapper(localName = "getServInfoResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "com.skywell.banking.api.ws.serv.GetServInfoResponse")
    public ServInfoRp getServInfo(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        ReqBase reqBase,
        @WebParam(name = "servId", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        String servId);

    /**
     * 
     * @param servId
     * @param reqBase
     * @param attrList
     * @return
     *     returns com.skywell.banking.api.ws.serv.ServOperRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
    @RequestWrapper(localName = "checkBalance", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "com.skywell.banking.api.ws.serv.CheckBalance")
    @ResponseWrapper(localName = "checkBalanceResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "com.skywell.banking.api.ws.serv.CheckBalanceResponse")
    public ServOperRp checkBalance(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        ReqBase reqBase,
        @WebParam(name = "servId", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        String servId,
        @WebParam(name = "attrList", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        List<AttrValue> attrList);

}
