
package com.skywell.banking.api.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServWebService", targetNamespace = "http://cb.ukrpay.net/common/ws", wsdlLocation = "http://10.1.15.19:7001/backend/common/servapi/?wsdl")
public class ServWebService_Service extends Service {

    private final static URL SERVWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVWEBSERVICE_EXCEPTION;
    private final static QName SERVWEBSERVICE_QNAME = new QName("http://cb.ukrpay.net/common/ws", "ServWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.15.19:7001/backend/common/servapi/?wsdl");
        } catch (MalformedURLException e1) {
            e1.printStackTrace();
        }
        SERVWEBSERVICE_WSDL_LOCATION = url;
        SERVWEBSERVICE_EXCEPTION = e;
    }

    public ServWebService_Service() {
        super(__getWsdlLocation(), SERVWEBSERVICE_QNAME);
    }

    public ServWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVWEBSERVICE_QNAME, features);
    }

    public ServWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVWEBSERVICE_QNAME);
    }

    public ServWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVWEBSERVICE_QNAME, features);
    }

    public ServWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns ServWebService
     */
    @WebEndpoint(name = "ServWebServiceSOAPHttpPort")
    public ServWebService getServWebServiceSOAPHttpPort() {
        return super.getPort(new QName("http://cb.ukrpay.net/common/ws", "ServWebServiceSOAPHttpPort"),
                ServWebService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns ServWebService
     */
    @WebEndpoint(name = "ServWebServiceSOAPHttpPort")
    public ServWebService getServWebServiceSOAPHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cb.ukrpay.net/common/ws", "ServWebServiceSOAPHttpPort"),
                ServWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVWEBSERVICE_EXCEPTION != null) {
            throw SERVWEBSERVICE_EXCEPTION;
        }
        return SERVWEBSERVICE_WSDL_LOCATION;
    }

}
