
package com.skywell.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.skywell.ws.core.CurrencyListRp;
import com.skywell.ws.core.ExchRateListRp;
import com.skywell.ws.core.LangListRp;
import com.skywell.ws.core.NewsListRp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BaseWebService", targetNamespace = "http://cb.ukrpay.net/common/ws")
@XmlSeeAlso({
        com.skywell.ws.ObjectFactory.class,
        com.skywell.ws.core.ObjectFactory.class
})
public interface BaseWebService {


    /**
     * 
     * @param reqBase
     * @return
     *     returns com.skywell.ws.core.LangListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/core")
    @RequestWrapper(localName = "getLangList", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetLangList")
    @ResponseWrapper(localName = "getLangListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetLangListResponse")
    public LangListRp getLangList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/core")
        ReqBase reqBase);

    /**
     * 
     * @param reqBase
     * @return
     *     returns com.skywell.ws.core.CurrencyListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/core")
    @RequestWrapper(localName = "getCurrencyList", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetCurrencyList")
    @ResponseWrapper(localName = "getCurrencyListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetCurrencyListResponse")
    public CurrencyListRp getCurrencyList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/core")
        ReqBase reqBase);

    /**
     * 
     * @param reqBase
     * @return
     *     returns com.skywell.ws.core.CurrencyListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/core")
    @RequestWrapper(localName = "getCurrencyAllList", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetCurrencyAllList")
    @ResponseWrapper(localName = "getCurrencyAllListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetCurrencyAllListResponse")
    public CurrencyListRp getCurrencyAllList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/core")
        ReqBase reqBase);

    /**
     * 
     * @param fltCurrencyId
     * @param reqBase
     * @param fltCurrencyType
     * @param fltExchType
     * @return
     *     returns com.skywell.ws.core.ExchRateListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/core")
    @RequestWrapper(localName = "getExchRateList", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetExchRateList")
    @ResponseWrapper(localName = "getExchRateListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetExchRateListResponse")
    public ExchRateListRp getExchRateList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/core")
        ReqBase reqBase,
        @WebParam(name = "fltExchType", targetNamespace = "http://cb.ukrpay.net/common/ws/core")
        String fltExchType,
        @WebParam(name = "fltCurrencyType", targetNamespace = "http://cb.ukrpay.net/common/ws/core")
        String fltCurrencyType,
        @WebParam(name = "fltCurrencyId", targetNamespace = "http://cb.ukrpay.net/common/ws/core")
        int fltCurrencyId);

    /**
     * 
     * @param reqBase
     * @return
     *     returns com.skywell.ws.core.NewsListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/core")
    @RequestWrapper(localName = "getNewsList", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetNewsList")
    @ResponseWrapper(localName = "getNewsListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/core", className = "com.skywell.ws.core.GetNewsListResponse")
    public NewsListRp getNewsList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/core")
        ReqBase reqBase);

}
