
package src;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BaseWebService", targetNamespace = "http://cb.ukrpay.net/common/ws", wsdlLocation = "http://10.1.15.19:7001/backend/common/api.baseapi/?wsdl")
public class BaseWebService_Service
    extends Service
{

    private final static URL BASEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BASEWEBSERVICE_EXCEPTION;
    private final static QName BASEWEBSERVICE_QNAME = new QName("http://cb.ukrpay.net/common/ws", "BaseWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.15.19:7001/backend/common/api.baseapi/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASEWEBSERVICE_WSDL_LOCATION = url;
        BASEWEBSERVICE_EXCEPTION = e;
    }

    public BaseWebService_Service() {
        super(__getWsdlLocation(), BASEWEBSERVICE_QNAME);
    }

    public BaseWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASEWEBSERVICE_QNAME, features);
    }

    public BaseWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, BASEWEBSERVICE_QNAME);
    }

    public BaseWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASEWEBSERVICE_QNAME, features);
    }

    public BaseWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaseWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BaseWebService
     */
    @WebEndpoint(name = "BaseWebServiceSOAPHttpPort")
    public BaseWebService getBaseWebServiceSOAPHttpPort() {
        return super.getPort(new QName("http://cb.ukrpay.net/common/ws", "BaseWebServiceSOAPHttpPort"), BaseWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaseWebService
     */
    @WebEndpoint(name = "BaseWebServiceSOAPHttpPort")
    public BaseWebService getBaseWebServiceSOAPHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cb.ukrpay.net/common/ws", "BaseWebServiceSOAPHttpPort"), BaseWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASEWEBSERVICE_EXCEPTION!= null) {
            throw BASEWEBSERVICE_EXCEPTION;
        }
        return BASEWEBSERVICE_WSDL_LOCATION;
    }

}
