
package api.userapi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "http://cb.ukrpay.net/common/ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param reqBase
     * @param hashPassword
     * @param login
     * @return
     *     returns api.userapi.SessionRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.AuthenticateResponse")
    public SessionRp authenticate(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase,
        @WebParam(name = "login", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String login,
        @WebParam(name = "hashPassword", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String hashPassword);

    /**
     * 
     * @param reqBase
     * @return
     *     returns api.userapi.SessionRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "checkSession", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CheckSession")
    @ResponseWrapper(localName = "checkSessionResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CheckSessionResponse")
    public SessionRp checkSession(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase);

    /**
     * 
     * @param reqBase
     * @return
     *     returns api.userapi.ResultRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "logout", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.LogoutResponse")
    public ResultRp logout(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase);

    /**
     * 
     * @param reqBase
     * @param otpReqId
     * @param otpPass
     * @return
     *     returns api.userapi.SessionRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "checkAuthOtp", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CheckAuthOtp")
    @ResponseWrapper(localName = "checkAuthOtpResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CheckAuthOtpResponse")
    public SessionRp checkAuthOtp(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase,
        @WebParam(name = "otpReqId", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String otpReqId,
        @WebParam(name = "otpPass", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String otpPass);

    /**
     * 
     * @param code
     * @param reqBase
     * @param login
     * @return
     *     returns api.userapi.SessionRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "checkAccessCode", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CheckAccessCode")
    @ResponseWrapper(localName = "checkAccessCodeResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CheckAccessCodeResponse")
    public SessionRp checkAccessCode(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase,
        @WebParam(name = "login", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String login,
        @WebParam(name = "code", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String code);

    /**
     * 
     * @param hashNewPassword
     * @param reqBase
     * @param hashCurrentPassword
     * @param login
     * @return
     *     returns api.userapi.SessionRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "changePass", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.ChangePass")
    @ResponseWrapper(localName = "changePassResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.ChangePassResponse")
    public SessionRp changePass(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase,
        @WebParam(name = "login", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String login,
        @WebParam(name = "hashCurrentPassword", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String hashCurrentPassword,
        @WebParam(name = "hashNewPassword", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String hashNewPassword);

    /**
     * 
     * @param hashNewPassword
     * @param reqBase
     * @param login
     * @return
     *     returns api.userapi.SessionRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "restorePass", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.RestorePass")
    @ResponseWrapper(localName = "restorePassResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.RestorePassResponse")
    public SessionRp restorePass(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase,
        @WebParam(name = "login", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String login,
        @WebParam(name = "hashNewPassword", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String hashNewPassword);

    /**
     * 
     * @param reqBase
     * @return
     *     returns api.userapi.UserPassCfgRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "getPassCfg", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.GetPassCfg")
    @ResponseWrapper(localName = "getPassCfgResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.GetPassCfgResponse")
    public UserPassCfgRp getPassCfg(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase);

    /**
     * 
     * @param listCheckUserVar
     * @param reqBase
     * @param hashPassword
     * @param login
     * @return
     *     returns api.userapi.CreateUserRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "createUserPrepare", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CreateUserPrepare")
    @ResponseWrapper(localName = "createUserPrepareResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CreateUserPrepareResponse")
    public CreateUserRp createUserPrepare(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase,
        @WebParam(name = "listCheckUserVar", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        List<CheckUserVar> listCheckUserVar,
        @WebParam(name = "login", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String login,
        @WebParam(name = "hashPassword", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String hashPassword);

    /**
     * 
     * @param reqBase
     * @param otpReqId
     * @param otpPass
     * @return
     *     returns api.userapi.CreateUserRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/user")
    @RequestWrapper(localName = "createUserOtp", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CreateUserOtp")
    @ResponseWrapper(localName = "createUserOtpResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/user", className = "api.userapi.CreateUserOtpResponse")
    public CreateUserRp createUserOtp(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        ReqBase reqBase,
        @WebParam(name = "otpReqId", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String otpReqId,
        @WebParam(name = "otpPass", targetNamespace = "http://cb.ukrpay.net/common/ws/user")
        String otpPass);

}
