
package servapi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServWebService", targetNamespace = "http://cb.ukrpay.net/common/ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServWebService {


    /**
     * 
     * @param reqBase
     * @param parentId
     * @return
     *     returns servapi.CategoryListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
    @RequestWrapper(localName = "getCategoryList", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "servapi.GetCategoryList")
    @ResponseWrapper(localName = "getCategoryListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "servapi.GetCategoryListResponse")
    public CategoryListRp getCategoryList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        ReqBase reqBase,
        @WebParam(name = "parentId", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        int parentId);

    /**
     * 
     * @param reqBase
     * @param categoryId
     * @return
     *     returns servapi.ServListRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
    @RequestWrapper(localName = "getServList", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "servapi.GetServList")
    @ResponseWrapper(localName = "getServListResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "servapi.GetServListResponse")
    public ServListRp getServList(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        ReqBase reqBase,
        @WebParam(name = "categoryId", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        int categoryId);

    /**
     * 
     * @param servId
     * @param reqBase
     * @return
     *     returns servapi.ServInfoRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
    @RequestWrapper(localName = "getServInfo", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "servapi.GetServInfo")
    @ResponseWrapper(localName = "getServInfoResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "servapi.GetServInfoResponse")
    public ServInfoRp getServInfo(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        ReqBase reqBase,
        @WebParam(name = "servId", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        String servId);

    /**
     * 
     * @param servId
     * @param reqBase
     * @param attrList
     * @return
     *     returns servapi.ServOperRp
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
    @RequestWrapper(localName = "checkBalance", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "servapi.CheckBalance")
    @ResponseWrapper(localName = "checkBalanceResponse", targetNamespace = "http://cb.ukrpay.net/common/ws/serv", className = "servapi.CheckBalanceResponse")
    public ServOperRp checkBalance(
        @WebParam(name = "reqBase", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        ReqBase reqBase,
        @WebParam(name = "servId", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        String servId,
        @WebParam(name = "attrList", targetNamespace = "http://cb.ukrpay.net/common/ws/serv")
        List<AttrValue> attrList);

}
